Z7.1: Testy jednostkowe
bikol/DINO202223-testing pull request #5
Opened 2022-11-30 02:23 UTC by s473573

2022-11-30 13:38 UTC, bikol requested changes
proszę zrobic merge z obecną wersją kodu

2022-12-01 18:12 UTC, s473573 commented
> proszę zrobic merge z obecną wersją kodu

conflicts resolved

2022-12-21 08:16 UTC, bikol requested changes
Niestety ale trzeba jeszcze raz zmergować, oby tym razem nikt nie był szybszy

2023-01-05 09:56 UTC, bikol reviewed
zmergowałem

2023-01-05 10:03 UTC, merged